/**
 * Define the navigation map of each view.
 *
 * @example
 * 'this-view': [ 'can-go-to-this-other-view' ]
 */
export default {
	'global': [
		'transfers',
		'personal-area',
		'product',
		'product-group',
		'premium',
		'managed-portfolio',
		'communications',
		'signatures',
		'bizum-dashboard',
		'profiles-dashboard',
		'ontime-dashboard',
	],
	'transfers': ['transfer', 'my-transfers', 'personal-area', 'bizum', 'correos-cash-dashboard'],
	'bizum': ['bizum-welcome', 'bizum-dashboard'],
	'bizum-welcome': ['bizum-register'],
	'bizum-register': ['bizum-dashboard'],
	'bizum-dashboard': ['bizum-movement', 'bizum-transfer'],
	'bizum-movement': ['bizum-transfer'],
	'correos-cash-dashboard': ['correos-cash-deposit', 'correos-cash-detail'],
	'my-transfers': ['transfer-detail'],
	'customer-service': ['customer-chat', 'customer-online', 'customer-offices', 'sirvase'],
	'personal-area': ['language', 'change-password', 'personal-details'],
	'feedback': [],
	'linea-caminos': [],
	'transfer-detail': ['transfer'],
	'product-group': ['product'],
	'product': [
		'movement',
		'search-movements',
		'amortization-table',
		'receipts-table',
		'imposition',
		'asset',
		'transfer',
		'my-transfers',
		'composition',
		'product-profiles',
		'sirvase-create',
	],
	'composition': ['investment-asset'],
	'managed-portfolio': ['product'],
	'premium': ['product'],
	'asset': ['movement', 'search-movements'],
	'search-movements': [],
	'communications': ['communication-detail'],
	'signatures': ['signature-detail'],
	'profiles': ['profiles-welcome', 'profiles-dashboard'],
	'profiles-dashboard': ['profiles-create'],
	'profiles-welcome': ['profiles-create'],
	'product-profiles': ['profiles-create'],
	'ontime': ['ontime-welcome', 'ontime-dashboard'],
	'ontime-dashboard': ['ontime-welcome', 'ontime-create', 'movement'],
	'ontime-welcome': ['ontime-create'],
	'sirvase': ['sirvase-welcome', 'sirvase-dashboard'],
	'sirvase-dashboard': ['sirvase-welcome', 'sirvase-create', 'sirvase-detail'],
	'sirvase-welcome': ['sirvase-create'],
	'movement': ['sirvase-create'],
};
